version: "3.8"
services:
  mongodb:
    container_name: cs-help-mongodb
    image: mongo:4.4.6
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 7017:27017
