version: "3.8"
services:
  mongodb:
    container_name: cs-help-mongodb
    image: mongo:5.0.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    # # uncomment the following to skip ALL logging for this container
    # # ideally we find a way to skip stdout logging on the `docker-compose` command,
    # # but preserve the file logging that the default driver "json-file" uses
    # # https://stackoverflow.com/questions/34590317/disable-logging-for-one-container-in-docker-compose
    # logging:
    #   driver: json-file
  app-backend:
    container_name: cs-help-server
    build: ./cs-help-server
    depends_on:
      - mongodb
    volumes:
      - ./cs-help-server:/cs-help-server
      - /cs-help-server/node_modules
    command: nodemon app.js
    restart: unless-stopped
    env_file: ./.env
    expose:
      - $NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - GOOGLE_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_SECRET=$GOOGLE_CLIENT_SECRET
      - MICROSOFT_ID=$MICROSOFT_CLIENT_ID
      - MICROSOFT_SECRET=$MICROSOFT_CLIENT_SECRET
    stdin_open: true
    tty: true
  app-frontend:
    container_name: cs-help-frontend
    depends_on:
      - mongodb
    build: ./pbp
    volumes:
      - ./pbp:/cs-help-pbp
      - /cs-help-pbp/node_modules
    restart: unless-stopped
    expose:
      - $VUE_DOCKER_PORT
    stdin_open: true
    tty: true
  nginx:
    container_name: cs-help-nginx
    depends_on:
      - app-frontend
      - app-backend
    restart: always
    build:
      context: ./nginx
    ports:
      - "3060:80"
    # logging:
    #   driver: none
volumes:
  db:
