
name: CS-Help backend unit-test

on:
  push:
    branches: [ backend-login ]
  pull_request:
    branches: [ backend-login ]

jobs:
  build:

    runs-on: x64

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: docker-compose -f .github/docker-compose-mongo.yml up --build -d
    - run: npm install
      working-directory: cs-help-server
    - run: npm ci
      working-directory: cs-help-server
    - run: npm run test
      working-directory: cs-help-server
    - run: docker-compose -f .github/docker-compose-mongo.yml down --volumes