
name: CS-Help backend unit-test

on:
  push:
    branches: [ backend-login ]
  pull_request:
    branches: [ backend-login ]

defaults:
  run:
    working-directory: cs-help-server

jobs:
  build:

    runs-on: x64

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: rm package-lock.json && rm -rf node_modules && rm -rf ~/.node-gyp
    - run: npm install -g node-gyp
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: docker --version
    - run: npm run test
      working-directory: cs-help-server